algoritmo "FazSomaProcedimento"
// ==========================================================
// Procedimento recebe um par?metro do tipo valor
// ==========================================================
var
   X, Y: Inteiro
procedimento Soma(A, B: Inteiro)
inicio
      escreval("Recebi o valor", A)
      escreval("Recebi o valor", B)
      escreval("A soma entre esses valores ?:", A + B)
fimprocedimento
inicio
      X <- 5
      Y <- 3
      Soma(X, Y)
fimalgoritmo