algoritmo "primeiro"
// +---------------------------------------------------+
// Disciplina [Lógica de Programação / Algoritmo]
// Função: Escrever "Olá, mundo!" na tela.
// Autor: João Paulo Pinheiro do Nascimento
// Info: Exemplo disponibilizado pelo Canal CursoEmVideo
// +---------------------------------------------------+
var
   msg: caractere
inicio

   msg <- "Olá, Mundo!"
   escreval("+-------===== S A Í D A =====-------+")
   escreva(msg, " Me livrei da maldição!")
   
fimalgoritmo