algoritmo "contador"
// Disciplina : [Lógica de Programação / Algoritmo]
// Professor  : Gustavo Guanabara - Curso Em Video
// Descrição  : Contar de 1 até 10 usando a estrutura PARA
// Autor(a)   : João Paulo Pinheiro Nascimento
var
   contador: Inteiro {Declaração de Variáveis}
inicio

   // Imprimir na tela a contegem de 1 até 10.
   Escreval("|- CONTADOR -|")
   Para contador <- 1 ate 10 passo 1 faca
      Escreval(contador)
   FimPara
   Escreval("|------------|")

fimalgoritmo