algoritmo "olaMundo"
// =====================================================================
// ! Escreva um programa que mostre na tela a mensagem "Olá, Mundo!"
//
// Autor: João Paulo Pinheiro do Nascimento
//(PASSO01) Desafio do CursoEmVideo Resolvido - Prof°: Gustavo Guanabara
// =====================================================================
var
inicio
   Escreval("|------ DESAFIO 001 ------|")
   Escreval(" Olá, Mundo! Estou pronto!")
fimalgoritmo